apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "block-external-world"
spec:
  endpointSelector:
    matchLabels:
      run: tracer
  egress:
  - toEntities:
    - cluster
    - kube-apiserver
